### ISSUE TITLE
More than 20 resources

### ISSUE THREAD

**Issue by lauriarnold** [EscherLabs/Graphene#200] opened 2022-02-22 17:04 UTC
Having a problem when more than 20 resources are defined

Look at BUFAP Admin (bu fine arts practicum) has 24 resource on mercury.  Trying to convert to hermes and after 20 resources errors start occurring.

**Comment by timcortesi** [comment] 2022-02-22 17:05
Closing this as a duplicate of https://github.com/EscherLabs/Graphene/issues/199

**Closed by timcortesi** 2022-02-22 17:05 UTC
Labels: bug, duplicate
