### ISSUE TITLE
Graphene Workflows: Issues with File Uploads and File Management for 'open' Workflows

### ISSUE THREAD

**Issue by timcortesi** [EscherLabs/Graphene#101] opened 2020-12-21 20:54 UTC
> Notice: Managing files for workflows which have not yet been submitted seems to work more/less correctly.  This bug report is only referencing the way in which files are managed within a form (when being edited in a popup modal) that has already been submitted.

To reproduce:
1. Open a workflow which has been submitted
2. Trigger an action which brings up the form in a modal
3. Click on the "down arrow" of a "file" type form field to list all available files.

Issue 1:
Note that only image file types are rendered correctly in the dropdown of the "file" type form field.  Other document types like PDF or DOC do not render correctly.  
<img width="306" alt="Screen Shot 2020-12-21 at 3 46 46 PM" src="https://user-images.githubusercontent.com/5395437/102820941-1cb12100-43a4-11eb-883f-d3ca35bbf515.png">
(Note that these look fine when uploading files on a workflow that hasn't been submitted yet)

Issue 2:
If you click "Upload New File", the file _does_ indeed get uploaded, but it is not visible in the dropdown.  You have to actually refresh the page in order to view the newly uploaded file in the dropdown menu.
<img width="304" alt="Screen Shot 2020-12-21 at 3 50 39 PM" src="https://user-images.githubusercontent.com/5395437/102821065-639f1680-43a4-11eb-8e29-1f8668b60293.png">
(Note this too works fine when uploading files on a workflow that hasn't been submitted yet)

Marking this as a relatively high priority, as file management seems sub-optimal at the current time.  For more info, and examples, please reach out to @alikemaltanriverdi

**Comment by timcortesi** [comment] 2020-12-25 15:01
Assigning to @alikemaltanriverdi to test in http://portalawsdev.binghamton.edu

**Comment by alikemaltanriverdi** [comment] 2020-12-30 21:40
- Everything seems to be working regarding the file uploads and list of the files in the file upload fields. 
- One issue I have encountered is that if the uploaded file name doesn't include the characters those were entered in the search box earlier, it doesn't select the file automatically. You need to delete your searched text to see the updated file list. Please see the screenshot below:
<img width="1677" alt="Screen Shot 2020-12-30 at 4 38 58 PM" src="https://user-images.githubusercontent.com/11221504/103382565-88d70780-4abd-11eb-81fd-9ee3bb6826db.png">

If this is an expected behaviour, you can ignore it and close the issue.

**Comment by timcortesi** [comment] 2020-12-30 22:40
Assigning back to @Cloverstone to review feedback from test above.

**Comment by timcortesi** [comment] 2021-01-05 20:09
Assigning to @alikemaltanriverdi to test

**Closed** 2021-02-12 14:25 UTC
Labels: awaiting test, bug, high priority, workflows
